### ISSUE TITLE
[unsure] Sci-fi theme give me this problem

### ISSUE THREAD

**Issue by Ramy-Ashraf** [KaranRaval123/Sci-fi#3]
![image](https://github.com/KaranRaval123/Sci-fi/assets/85342902/33ee3939-3eac-43f5-99b4-8118f5aed51c)
how to solve it?

**Comment by KaranRaval123** [comment]
Hey, thanks for bringing up the issue. My bad I just switched from Endeavour to vanilla Arch and didn't realize pushing my local changes would mess things up without the wallbash script. Anyway, I've rolled back the changes. You can either patch theme again or just copy 'hypr.theme' and replace your original file at '~/.config/hyde/themes/Sci-fi' on your computer. Feel free to ask if you have any more questions or need further help

**Comment by Ramy-Ashraf** [comment]
yah... it now works great.
thanks for your effort 🫡 .
